//
//  Colors.swift
//  SharedDesignSystem
//
//  Created by 박현우 on 2023/05/24.
//

import Foundation
import SwiftUI

public extension Color {
    static let colorBlue100 = Color(asset: SharedDesignSystemAsset.colorBlue100)
    static let colorBlue200 = Color(asset:SharedDesignSystemAsset.colorBlue200)
    static let colorBlue300 = Color(asset:SharedDesignSystemAsset.colorBlue300)
    static let colorBlue400 = Color(asset:SharedDesignSystemAsset.colorBlue400)
    static let colorBlue50 = Color(asset:SharedDesignSystemAsset.colorBlue50)
    static let colorBlue500 = Color(asset:SharedDesignSystemAsset.colorBlue500)
    static let colorBlue600 = Color(asset:SharedDesignSystemAsset.colorBlue600)
    static let colorBlue700 = Color(asset:SharedDesignSystemAsset.colorBlue700)
    static let colorBlue800 = Color(asset:SharedDesignSystemAsset.colorBlue800)
    static let colorBlue900 = Color(asset:SharedDesignSystemAsset.colorBlue900)
    static let colorBluePrimary = Color(asset:SharedDesignSystemAsset.colorBluePrimary)
    static let colorCyan100 = Color(asset:SharedDesignSystemAsset.colorCyan100)
    static let colorCyan200 = Color(asset:SharedDesignSystemAsset.colorCyan200)
    static let colorCyan300 = Color(asset:SharedDesignSystemAsset.colorCyan300)
    static let colorCyan400 = Color(asset:SharedDesignSystemAsset.colorCyan400)
    static let colorCyan50 = Color(asset:SharedDesignSystemAsset.colorCyan50)
    static let colorCyan500 = Color(asset:SharedDesignSystemAsset.colorCyan500)
    static let colorCyan600 = Color(asset:SharedDesignSystemAsset.colorCyan600)
    static let colorCyan700 = Color(asset:SharedDesignSystemAsset.colorCyan700)
    static let colorCyan800 = Color(asset:SharedDesignSystemAsset.colorCyan800)
    static let colorCyan900 = Color(asset:SharedDesignSystemAsset.colorCyan900)
    static let colorCyanPrimary = Color(asset:SharedDesignSystemAsset.colorCyanPrimary)
    static let colorGreen100 = Color(asset:SharedDesignSystemAsset.colorGreen100)
    static let colorGreen200 = Color(asset:SharedDesignSystemAsset.colorGreen200)
    static let colorGreen300 = Color(asset:SharedDesignSystemAsset.colorGreen300)
    static let colorGreen400 = Color(asset:SharedDesignSystemAsset.colorGreen400)
    static let colorGreen50 = Color(asset:SharedDesignSystemAsset.colorGreen50)
    static let colorGreen500 = Color(asset:SharedDesignSystemAsset.colorGreen500)
    static let colorGreen600 = Color(asset:SharedDesignSystemAsset.colorGreen600)
    static let colorGreen700 = Color(asset:SharedDesignSystemAsset.colorGreen700)
    static let colorGreen800 = Color(asset:SharedDesignSystemAsset.colorGreen800)
    static let colorGreen900 = Color(asset:SharedDesignSystemAsset.colorGreen900)
    static let colorGreenPrimary = Color(asset:SharedDesignSystemAsset.colorGreenPrimary)
    static let colorTeal100 = Color(asset:SharedDesignSystemAsset.colorTeal100)
    static let colorTeal200 = Color(asset:SharedDesignSystemAsset.colorTeal200)
    static let colorTeal300 = Color(asset:SharedDesignSystemAsset.colorTeal300)
    static let colorTeal400 = Color(asset:SharedDesignSystemAsset.colorTeal400)
    static let colorTeal50 = Color(asset:SharedDesignSystemAsset.colorTeal50)
    static let colorTeal500 = Color(asset:SharedDesignSystemAsset.colorTeal500)
    static let colorTeal600 = Color(asset:SharedDesignSystemAsset.colorTeal600)
    static let colorTeal700 = Color(asset:SharedDesignSystemAsset.colorTeal700)
    static let colorTeal800 = Color(asset:SharedDesignSystemAsset.colorTeal800)
    static let colorTeal900 = Color(asset:SharedDesignSystemAsset.colorTeal900)
    static let colorTealPrimary = Color(asset:SharedDesignSystemAsset.colorTealPrimary)
    static let colorGrey000 = Color(asset:SharedDesignSystemAsset.colorGrey000)
    static let colorGrey50 = Color(asset:SharedDesignSystemAsset.colorGrey50)
    static let colorGrey100 = Color(asset:SharedDesignSystemAsset.colorGrey100)
    static let colorGrey200 = Color(asset:SharedDesignSystemAsset.colorGrey200)
    static let colorGrey300 = Color(asset:SharedDesignSystemAsset.colorGrey300)
    static let colorGrey400 = Color(asset:SharedDesignSystemAsset.colorGrey400)
    static let colorGrey500 = Color(asset:SharedDesignSystemAsset.colorGrey500)
    static let colorGrey600 = Color(asset:SharedDesignSystemAsset.colorGrey600)
    static let colorGrey700 = Color(asset:SharedDesignSystemAsset.colorGrey700)
    static let colorGrey800 = Color(asset:SharedDesignSystemAsset.colorGrey800)
    static let colorGrey900 = Color(asset:SharedDesignSystemAsset.colorGrey900)
}
